
name: Build, Tests and Deploy Titanic Story - Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build Titanic's Story  
      run: npm install 
           node server.js
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy application to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api-key: ${{ secrets.MY_RENDER_API_KEY }}  

  runs-ui-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies for application
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run UI tests
      run: npm run test:ui